application: mardict
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /user/.*
  script: app.py
  login: required

- url: /god/.*
  script: app.py
  login: admin 

- url: /.*
  script: app.py

inbound_services:
- xmpp_message
